// ─── DADOS DA EQUIPE ─────────────────────────────────────────────────────────

export const PEOPLE = {
  Emanoel:        { color: "#7B1FA2", bg: "#F3E5F5" },
  "Marcus Túlio": { color: "#2E7D32", bg: "#E8F5E9" },
  Ricardo:        { color: "#1565C0", bg: "#E3F2FD" },
  Carlos:         { color: "#37474F", bg: "#ECEFF1" },
  Raul:           { color: "#E65100", bg: "#FFF3E0" },
  Alice:          { color: "#AD1457", bg: "#FCE4EC" },
};

export const CH_NAMES = ["Raul", "Emanoel", "Marcus Túlio", "Ricardo", "Carlos", "Alice"];

// ─── DADOS DA ESCALA ─────────────────────────────────────────────────────────

export const WEEKDAY_SHIFTS = {
  1: [
    { period: "Madrugada", time: "23:00 – 04:00", dur: "5h", person: "Raul" },
    { period: "Manhã",     time: "04:00 – 09:00", dur: "5h", person: "Emanoel" },
    { period: "Noite",     time: "18:00 – 23:00", dur: "5h", person: "Marcus Túlio" },
  ],
  2: [
    { period: "Madrugada", time: "23:00 – 04:00", dur: "5h", person: "Ricardo" },
    { period: "Manhã",     time: "04:00 – 09:00", dur: "5h", person: "Carlos" },
    { period: "Noite",     time: "18:00 – 23:00", dur: "5h", person: "Raul" },
  ],
  3: [
    { period: "Madrugada", time: "23:00 – 04:00", dur: "5h", person: "Marcus Túlio" },
    { period: "Manhã",     time: "04:00 – 09:00", dur: "5h", person: "Emanoel" },
    { period: "Noite",     time: "18:00 – 23:00", dur: "5h", person: "Raul" },
  ],
  4: [
    { period: "Madrugada", time: "23:00 – 04:00", dur: "5h", person: "Ricardo" },
    { period: "Manhã",     time: "04:00 – 09:00", dur: "5h", person: "Marcus Túlio" },
    { period: "Noite",     time: "18:00 – 23:00", dur: "5h", person: "Carlos" },
  ],
  5: [
    { period: "Madrugada", time: "23:00 – 04:00", dur: "5h", person: "Emanoel" },
    { period: "Manhã",     time: "04:00 – 09:00", dur: "5h", person: "Raul" },
    // A Noite de sexta ia até 24:00, sobrepondo 1h ao "Dia" de sábado, que começa às
    // 23:00 de sexta — as duas pessoas ficavam de sobreaviso na mesma hora e ambas
    // recebiam por ela. Corrigida para 23:00 a partir de FRIDAY_NIGHT_CHANGE; a entrada
    // antiga permanece com vigência fechada para preservar o histórico e a folha já
    // paga de junho/julho de 2026. ⚠ Mover essas datas recalcula a escala.
    { period: "Noite",     time: "18:00 – 24:00", dur: "6h", person: "Ricardo", until: "2026-07-31" },
    { period: "Noite",     time: "18:00 – 23:00", dur: "5h", person: "Ricardo", from:  "2026-08-01" },
  ],
};

// Data em que a Noite de sexta passou a terminar às 23:00 (ver WEEKDAY_SHIFTS[5]).
export const FRIDAY_NIGHT_CHANGE = "2026-08-01";

// Rotação de FDS ANTIGA (5 semanas, 5 pessoas, 1 folga) — vale para os fins de
// semana ANTES de WEEKEND_CHANGE. Mantida para preservar o histórico/folha.
export const WEEKEND_CYCLE = [
  { sabDia: "Carlos",       sabNoite: "Emanoel",      domDia: "Ricardo",      domNoite: "Raul",         folga: "Marcus Túlio" },
  { sabDia: "Marcus Túlio", sabNoite: "Carlos",       domDia: "Emanoel",      domNoite: "Ricardo",      folga: "Raul" },
  { sabDia: "Raul",         sabNoite: "Marcus Túlio", domDia: "Carlos",       domNoite: "Emanoel",      folga: "Ricardo" },
  { sabDia: "Ricardo",      sabNoite: "Raul",         domDia: "Marcus Túlio", domNoite: "Carlos",       folga: "Emanoel" },
  { sabDia: "Emanoel",      sabNoite: "Ricardo",      domDia: "Raul",         domNoite: "Marcus Túlio", folga: "Carlos" },
];

// Rotação de FDS NOVA — escada de 6 semanas com as 6 pessoas (4 trabalham + 2 folgam).
// A tabela inteira é GERADA a partir desta ordem de rodízio: cada pessoa avança uma
// estação por semana. Estações (em ordem): Sáb Dia, Sáb Noite, Dom Dia, Dom Noite,
// Folga, Folga. Vale para os fins de semana a partir de WEEKEND_CHANGE.
// Ordem derivada por CONTINUIDADE com o ciclo antigo: no último FDS antigo (11–12/07)
// a folga foi do Carlos; na virada ele folga de novo (2ª folga), Alice entra no Sáb Dia
// e os demais só avançam uma estação. Assim ninguém "salta" de posição.
export const WEEKEND_ROSTER = ["Alice", "Emanoel", "Ricardo", "Raul", "Marcus Túlio", "Carlos"];
// Sábado da Semana 1 da escada nova (18/07/2026). Fins de semana >= esta data usam a
// escada nova; anteriores mantêm WEEKEND_CYCLE. ⚠ Mover isto recalcula a escala.
export const WEEKEND_CHANGE = new Date(2026, 6, 18);

// The Saturday corresponding to Week 1 of the 5-week weekend rotation.
// Changing ANCHOR shifts the entire schedule history — requires full rotation recalibration.
export const ANCHOR      = new Date(2026, 5, 13);
// Window generated by buildSchedule(). To extend the schedule, update RANGE_END only.
export const RANGE_START = new Date(2026, 5, 8);
export const RANGE_END   = new Date(2027, 5, 30);

// ─── LABELS ──────────────────────────────────────────────────────────────────

export const DOW         = ["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"];
export const DOW_SHORT   = ["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"];
export const MONTHS      = ["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
export const MONTHS_SHORT = ["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"];

// ─── HELPERS ─────────────────────────────────────────────────────────────────

export const MS_DAY  = 86400000;
export const dayKey  = (d) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
export const sameDay = (a, b) => a.getFullYear()===b.getFullYear() && a.getMonth()===b.getMonth() && a.getDate()===b.getDate();
export const fmtDS   = (str) => str ? `${str.slice(8)}/${str.slice(5,7)}` : "";

export function durationHours(inicio, fim) {
  if (!inicio || !fim) return 0;
  const [hi, mi] = inicio.split(":").map(Number);
  const [hf, mf] = fim.split(":").map(Number);
  let start = hi * 60 + mi;
  let end   = hf * 60 + mf;
  if (end <= start) end += 24 * 60; // shift crosses midnight (e.g. 23:00–04:00)
  return (end - start) / 60;
}

// Soma as horas de uma lista de lançamentos MESCLANDO intervalos que se sobrepõem
// (união), em vez de somar cada um isolado — evita contar tempo em dobro quando o
// usuário registra duas atividades no mesmo período. Trata turnos que cruzam a
// meia-noite (fim <= início) e não funde lançamentos de dias diferentes.
// Só deve ser usado por tipo (HE com HE, Comp com Comp): tipos diferentes têm
// remuneração distinta e não devem se cancelar.
export function mergedHours(entries) {
  const dayIdx = (d) => {
    const [y, m, dd] = String(d).split("-").map(Number);
    return Date.UTC(y, m - 1, dd) / MS_DAY;
  };
  const intervals = entries
    .map(e => {
      const [hi, mi] = String(e.inicio || "").split(":").map(Number);
      const [hf, mf] = String(e.fim    || "").split(":").map(Number);
      if ([hi, mi, hf, mf].some(Number.isNaN)) return null;
      const base = dayIdx(e.data) * 1440;
      const s = base + hi * 60 + mi;
      let en  = base + hf * 60 + mf;
      if (en <= s) en += 1440; // cruza meia-noite
      return [s, en];
    })
    .filter(Boolean)
    .sort((a, b) => a[0] - b[0]);

  let total = 0, curS = null, curE = null;
  for (const [s, e] of intervals) {
    if (curS === null)      { curS = s; curE = e; }
    else if (s < curE)      { if (e > curE) curE = e; } // colide → estende a união
    else                    { total += curE - curS; curS = s; curE = e; } // gap → fecha bloco
  }
  if (curS !== null) total += curE - curS;
  return total / 60;
}

export function fmtHM(hoursDecimal) {
  const totalMin = Math.round(hoursDecimal * 60);
  const h = Math.floor(totalMin / 60);
  const m = totalMin % 60;
  return `${h}:${String(m).padStart(2, "0")}`;
}

export const brl = (v) => v.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

// ─── LÓGICA DE ESCALA ────────────────────────────────────────────────────────

// Returns 0–4 index into WEEKEND_CYCLE for the given Saturday.
// The "+5 before %5" keeps the result positive for dates before ANCHOR.
export function cycleIndex(saturday) {
  const diff = Math.round((saturday.getTime() - ANCHOR.getTime()) / (7 * MS_DAY));
  return ((diff % 5) + 5) % 5;
}

// Atribuição de FDS para um dado sábado, a partir de uma config de rotação genérica
// (team.rotacao — ver src/lib/teams.js): escolhe a rotação pela data:
//   • sábado < rotacao.change → ciclo legado (N semanas, 1 folga) — preserva histórico.
//   • sábado >= rotacao.change → escada, GERADA do rotacao.roster:
//     estação s na semana w = roster[(s - w) mod N]; cada pessoa avança 1 estação/semana.
// Retorna sempre { cycleWeek, sabDia, sabNoite, domDia, domNoite, folga: string[] }.
function resolveRotation(rotacao, saturday) {
  if (saturday.getTime() >= rotacao.change.getTime()) {
    const roster = rotacao.roster;
    const N = roster.length;
    const diff = Math.round((saturday.getTime() - rotacao.change.getTime()) / (7 * MS_DAY));
    const w = ((diff % N) + N) % N;
    const cell = (s) => roster[(((s - w) % N) + N) % N];
    return {
      cycleWeek: w + 1,
      sabDia: cell(0), sabNoite: cell(1), domDia: cell(2), domNoite: cell(3),
      folga: [cell(4), cell(5)],
    };
  }
  const { anchor, ciclos } = rotacao.legado;
  const diff = Math.round((saturday.getTime() - anchor.getTime()) / (7 * MS_DAY));
  const idx = ((diff % ciclos.length) + ciclos.length) % ciclos.length;
  const rot = ciclos[idx];
  return {
    cycleWeek: idx + 1,
    sabDia: rot.sabDia, sabNoite: rot.sabNoite, domDia: rot.domDia, domNoite: rot.domNoite,
    folga: [rot.folga],
  };
}

// Config de rotação da sustentação, montada a partir das constantes acima — mantida
// aqui (e não em teams.js) para que weekendAssignment() siga funcionando sem mudança
// de assinatura para quem já a importa (EstruturaEscala.jsx). src/lib/teams.js expõe
// a mesma config como TEAMS.sustentacao.rotacao para o motor genérico.
const SUSTENTACAO_ROTACAO = {
  dows: [0, 6],
  tipo: "escada",
  roster: WEEKEND_ROSTER,
  change: WEEKEND_CHANGE,
  turnos: {
    dia:   { period: "Dia",   time: "23:00 – 11:00", dur: "12h" },
    noite: { period: "Noite", time: "11:00 – 23:00", dur: "12h" },
  },
  legado: { tipo: "ciclo", anchor: ANCHOR, ciclos: WEEKEND_CYCLE },
};

// Mantido para compatibilidade com a aba Estrutura (EstruturaEscala.jsx), que só
// conhece a sustentação. buildSchedule() usa resolveRotation() diretamente com a
// config da equipe recebida — não passa por aqui.
export function weekendAssignment(saturday) {
  return resolveRotation(SUSTENTACAO_ROTACAO, saturday);
}

// Turnos de um dia-da-semana vigentes numa data. Uma entrada de `blocos` pode declarar
// vigência (`from`/`until`, YYYY-MM-DD inclusivos) — é como a estrutura é corrigida sem
// reescrever o passado. Dois pontos importantes:
//   • os campos de vigência não vazam para o turno retornado;
//   • a filtragem acontece ANTES da atribuição de `idx`, então dias com entradas de
//     vigências diferentes continuam produzindo os mesmos índices — os overrides já
//     gravados apontam para eles.
// Retorna null quando a equipe não tem cobertura naquele dia-da-semana.
export function blocosAtivos(blocos, dow, dateStr) {
  const lista = blocos?.[dow];
  if (!lista) return null;
  return lista
    .filter(s => (!s.from || dateStr >= s.from) && (!s.until || dateStr <= s.until))
    .map(({ from, until, ...s }) => s);
}

// Pessoas de um turno — normaliza `person` (string legada) e `persons[]` (multi).
// Todo leitor da escala deve usar isto em vez de acessar shift.person direto.
export function shiftPeople(shift) {
  if (shift?.persons?.length) return shift.persons;
  if (shift?.person) return [shift.person];
  return [];
}

// Parseia "HH:MM – HH:MM" (aceita –, — ou -) → { sh, sm, eh, em } ou null.
export function parseTimeRange(timeStr) {
  const parts = String(timeStr).split(/[–—-]/).map(s => s.trim());
  if (parts.length < 2) return null;
  const [sh, sm] = (parts[0] || "").split(":").map(Number);
  const [eh, em] = (parts[1] || "").split(":").map(Number);
  if ([sh, sm, eh, em].some(Number.isNaN)) return null;
  return { sh, sm, eh, em };
}

// team: definição da equipe (ver src/lib/teams.js) — obrigatório.
//   team.blocos:  { [dow]: [{ period, time, dur, person? }] } — turnos fixos por dia da
//                 semana; equipe sem cobertura naquele dow simplesmente não tem entrada.
//   team.rotacao: { dows, roster, change, turnos:{dia,noite}, legado:{anchor,ciclos} } | null
//                 — gera os turnos de fim de semana da sustentação (ver resolveRotation).
//   team.startsOn/endsOn: vigência ('YYYY-MM-DD' | null) — recorta contra RANGE_START/END.
// overrides: { [dayKey]: { [idx]: { person?|persons?, period, time, dur, editedAt } | null } }
//   - idx além dos turnos base vira um turno NOVO (feriados/dias custom).
//   - null reverte o slot base ao padrão (e remove um turno extra).
// labels: { [dayKey]: string } — rótulo opcional do dia (ex.: "Feriado").
// Cada turno retornado carrega um `idx` estável (a chave do override), usado pela UI
// para seleção/edição/remoção — não confie na posição no array.
export function buildSchedule(team, overrides = {}, labels = {}) {
  const days = [];
  const startsOn = team.startsOn ? new Date(`${team.startsOn}T00:00:00`) : RANGE_START;
  const endsOn   = team.endsOn   ? new Date(`${team.endsOn}T00:00:00`)   : RANGE_END;
  const rangeStart = Math.max(RANGE_START.getTime(), startsOn.getTime());
  const rangeEnd   = Math.min(RANGE_END.getTime(), endsOn.getTime());
  for (let t = rangeStart; t <= rangeEnd; t += MS_DAY) {
    const d = new Date(t);
    d.setHours(12, 0, 0, 0);
    const dow = d.getDay();
    const dk = dayKey(d);
    let base = [], folga = [], cycleWeek = null; // folga sempre array (vazio em dia útil)
    const bloco = blocosAtivos(team.blocos, dow, dk);
    if (bloco) {
      base = bloco;
    } else if (team.rotacao?.dows?.includes(dow)) {
      const sat = dow === 6 ? d : new Date(d.getTime() - MS_DAY);
      const rot = resolveRotation(team.rotacao, sat);
      cycleWeek = rot.cycleWeek;
      folga = rot.folga; // array (1 pessoa no ciclo legado, 2 na escada nova)
      // Handoff fixo às 23:00/11:00 — alinha o FDS ao mesmo horário de virada
      // dos dias úteis (23:00), então Sex→Sáb→Dom→Seg conectam sem exceção.
      const { dia, noite } = team.rotacao.turnos;
      base = dow === 6
        ? [{ ...dia, person: rot.sabDia }, { ...noite, person: rot.sabNoite }]
        : [{ ...dia, person: rot.domDia }, { ...noite, person: rot.domNoite }];
    }
    const ovDay = overrides[dk] || {};
    const ovIdxs = Object.keys(ovDay).map(Number).filter(Number.isInteger);
    const maxIdx = Math.max(base.length - 1, ...ovIdxs, -1);
    const shifts = [];
    for (let i = 0; i <= maxIdx; i++) {
      const b = base[i];
      const ov = ovDay[String(i)];
      if (ov === null) { if (b) shifts.push({ ...b, idx: i }); continue; } // reverte base; extra some
      if (ov) {
        const merged = { ...(b || {}), ...ov, idx: i };
        // Pessoas definidas explicitamente por override "travam" o turno: uma
        // substituição em que essa pessoa é titular NÃO redireciona mais este turno
        // (edição do admin vence a substituição). Só marca quando o override mexe
        // em pessoas — override só de horário/rótulo mantém a rotação base (e seus subs).
        if (ov.persons !== undefined || ov.person !== undefined) merged.personsOverridden = true;
        shifts.push(merged);
        continue;
      }
      if (b)           { shifts.push({ ...b, idx: i }); }
    }
    days.push({ date: new Date(d), dow, shifts, folga, cycleWeek, label: labels[dk] || null });
  }
  return days;
}

// Sequência ordenada de blocos de plantão com início/fim absolutos (ms), derivada
// do shift.time REAL (não de janelas fixas) — então edições de horário e turnos
// custom de feriado são refletidos. Convenção de atribuição de dia (ADR-0002):
//   • dayStart declara a hora em que o dia da equipe começa (ex.: "23:00" na
//     sustentação). Um turno cujo horário de início é >= dayStart (quando
//     dayStart > 00:00) é PERNOITE: pertence ao dia anterior no calendário.
//   • Demais turnos: começam em D no horário parseado; terminam em D (ou D+1 se
//     cruzam a meia-noite). Turnos extras (idx ≥ base) seguem a mesma regra —
//     não há mais tratamento especial por idx.
// Com o handoff do FDS às 23:00, domingo à noite termina 23:00 e a Madrugada de
// segunda começa 23:00 do domingo — sem o antigo caso especial de segunda.
// Cada segmento carrega `people` (array) — turno multi-pessoa é um único bloco.
// dayStart é OBRIGATÓRIO (sem default): um default de equipe errada desloca a
// escala em um dia sem erro visível — cada chamador deve passar o dayStart da
// equipe que está de fato consultando (team.dayStart).
export function buildOnCallSegments(schedule, dayStart) {
  const [dsH, dsM] = String(dayStart).split(":").map(Number);
  const dayStartMin = (dsH || 0) * 60 + (dsM || 0);
  const dayMs = (D, off, h, m) => {
    const d = new Date(D); d.setHours(0, 0, 0, 0);
    return d.getTime() + off * MS_DAY + (h * 60 + m) * 60000;
  };
  const segs = [];
  for (const day of schedule) {
    const D = day.date, ds = dayKey(D);
    for (const shift of day.shifts) {
      const tr = parseTimeRange(shift.time);
      if (!tr) continue;
      const startMin = tr.sh * 60 + tr.sm, endMin = tr.eh * 60 + tr.em;
      const crosses = endMin <= startMin; // termina no dia seguinte
      let start, end;
      if (dayStartMin > 0 && startMin >= dayStartMin) {
        // pernoite (começa depois do início do dia da equipe) → pertence à véspera
        start = dayMs(D, -1, tr.sh, tr.sm);
        end   = dayMs(D, crosses ? 0 : -1, tr.eh, tr.em);
      } else {
        start = dayMs(D, 0, tr.sh, tr.sm);
        end   = dayMs(D, crosses ? 1 : 0, tr.eh, tr.em);
      }
      segs.push({ start, end, people: shiftPeople(shift), personsOverridden: !!shift.personsOverridden, period: shift.period, time: shift.time, dateStr: ds, dow: day.dow });
    }
  }
  return segs.sort((a, b) => a.start - b.start);
}

// schedule: array de buildSchedule(team, overrides, labels). `subs` aplica substituições.
// dayStart é OBRIGATÓRIO — o da equipe cuja escala está em `schedule` (team.dayStart).
// Retorna quem está de plantão AGORA (pode ser mais de uma pessoa em feriado/turno
// multi-pessoa) ou null no vão sem plantão. `people` = [{ person, coveringFor }].
export function currentOnCall(now, schedule, subs = [], dayStart) {
  const segs = buildOnCallSegments(schedule, dayStart);
  const t = now.getTime();
  const hits = segs.filter(s => t >= s.start && t < s.end);
  if (!hits.length) return null;
  const people = [];
  for (const s of hits) for (const titular of s.people) {
    // Turno com pessoas travadas por override não aplica substituição (edição vence).
    const sub = s.personsOverridden ? null : getActiveSub(titular, s.dateStr, subs);
    people.push({ person: sub ? sub.substituto : titular, coveringFor: sub ? titular : null });
  }
  const primary = hits[0];
  return { people, label: `${DOW[primary.dow]} · ${primary.period}`, time: primary.time };
}

// Plantonista anterior e próximo em relação a `now`, com substituições aplicadas.
// dayStart é OBRIGATÓRIO — o da equipe cuja escala está em `schedule` (team.dayStart).
// Cada lado vem como { people: [nomes], hora }. `hora` formatada (HH:MM, com dia curto
// se for outro dia). Retorna null quando não há vizinho (bordas da escala).
export function adjacentOnCall(now, schedule, subs = [], dayStart) {
  const segs = buildOnCallSegments(schedule, dayStart);
  const t = now.getTime();
  const nowDay = dayKey(now);

  const fmtHora = (ms) => {
    const d = new Date(ms);
    const hm = `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`;
    return dayKey(d) === nowDay ? hm : `${DOW_SHORT[d.getDay()]} ${hm}`;
  };
  const shape = (s, ms) => {
    if (!s) return null;
    const people = s.people.map(titular => {
      const sub = s.personsOverridden ? null : getActiveSub(titular, s.dateStr, subs);
      return sub ? sub.substituto : titular;
    });
    return { people, hora: fmtHora(ms) };
  };

  const cur = segs.findIndex(s => t >= s.start && t < s.end);
  let prevSeg = null, nextSeg = null;
  if (cur !== -1) {
    prevSeg = segs[cur - 1] || null;
    nextSeg = segs[cur + 1] || null;
  } else {
    nextSeg = segs.find(s => s.start > t) || null;
    for (let i = segs.length - 1; i >= 0; i--) { if (segs[i].end <= t) { prevSeg = segs[i]; break; } }
  }
  return {
    anterior: shape(prevSeg, prevSeg?.end),   // quando terminou
    proximo:  shape(nextSeg, nextSeg?.start), // quando começa
  };
}

export function getActiveSub(person, dateStr, subs) {
  return subs.find(s => s.titular === person && dateStr >= s.from && dateStr <= s.until) || null;
}

// Resolve as pessoas EFETIVAS de um turno numa data, aplicando substituições.
// Regra "edição vence substituição": se as pessoas do turno foram definidas
// explicitamente por override do admin (`shift.personsOverridden`), a atribuição é
// final — uma substituição em que essa pessoa é titular NÃO redireciona este turno.
// Retorna [{ person, coveringFor, titular }] — `coveringFor` = titular coberto (ou null).
// Fonte única de verdade usada pelo calendário, filtro e cálculo do CH (folha).
export function resolveShiftPeople(shift, dateStr, subs = []) {
  const locked = !!shift?.personsOverridden;
  return shiftPeople(shift).map(titular => {
    const sub = locked ? null : getActiveSub(titular, dateStr, subs);
    return { person: sub ? sub.substituto : titular, coveringFor: sub ? titular : null, titular };
  });
}

export function getCoverSuggestions(titular, fromStr, untilStr, schedule) {
  return schedule
    .filter(d => {
      const k = dayKey(d.date);
      return k >= fromStr && k <= untilStr && d.shifts.some(s => shiftPeople(s).includes(titular));
    })
    .map(d => {
      const busy = new Set(d.shifts.flatMap(s => shiftPeople(s)));
      const available = Object.keys(PEOPLE).filter(p => p !== titular && !busy.has(p));
      return { date: d.date, dow: d.dow, shifts: d.shifts.filter(s => shiftPeople(s).includes(titular)), available };
    });
}
