// ─── DADOS DA EQUIPE ─────────────────────────────────────────────────────────

export const PEOPLE = {
  Emanoel:        { color: "#7B1FA2", bg: "#F3E5F5" },
  "Marcus Túlio": { color: "#2E7D32", bg: "#E8F5E9" },
  Ricardo:        { color: "#1565C0", bg: "#E3F2FD" },
  Carlos:         { color: "#37474F", bg: "#ECEFF1" },
  Raul:           { color: "#E65100", bg: "#FFF3E0" },
  Alice:          { color: "#AD1457", bg: "#FCE4EC" },
};

export const CH_NAMES = ["Raul", "Emanoel", "Marcus Túlio", "Ricardo", "Carlos", "Alice"];

// ─── DADOS DA ESCALA ─────────────────────────────────────────────────────────

export const WEEKDAY_SHIFTS = {
  1: [
    { period: "Madrugada", time: "23:00 – 04:00", dur: "5h", person: "Raul" },
    { period: "Manhã",     time: "04:00 – 09:00", dur: "5h", person: "Emanoel" },
    { period: "Noite",     time: "18:00 – 23:00", dur: "5h", person: "Marcus Túlio" },
  ],
  2: [
    { period: "Madrugada", time: "23:00 – 04:00", dur: "5h", person: "Ricardo" },
    { period: "Manhã",     time: "04:00 – 09:00", dur: "5h", person: "Carlos" },
    { period: "Noite",     time: "18:00 – 23:00", dur: "5h", person: "Raul" },
  ],
  3: [
    { period: "Madrugada", time: "23:00 – 04:00", dur: "5h", person: "Marcus Túlio" },
    { period: "Manhã",     time: "04:00 – 09:00", dur: "5h", person: "Emanoel" },
    { period: "Noite",     time: "18:00 – 23:00", dur: "5h", person: "Raul" },
  ],
  4: [
    { period: "Madrugada", time: "23:00 – 04:00", dur: "5h", person: "Ricardo" },
    { period: "Manhã",     time: "04:00 – 09:00", dur: "5h", person: "Marcus Túlio" },
    { period: "Noite",     time: "18:00 – 23:00", dur: "5h", person: "Carlos" },
  ],
  5: [
    { period: "Madrugada", time: "23:00 – 04:00", dur: "5h", person: "Emanoel" },
    { period: "Manhã",     time: "04:00 – 09:00", dur: "5h", person: "Raul" },
    { period: "Noite",     time: "18:00 – 24:00", dur: "6h", person: "Ricardo" },
  ],
};

// Rotação de FDS ANTIGA (5 semanas, 5 pessoas, 1 folga) — vale para os fins de
// semana ANTES de WEEKEND_CHANGE. Mantida para preservar o histórico/folha.
export const WEEKEND_CYCLE = [
  { sabDia: "Carlos",       sabNoite: "Emanoel",      domDia: "Ricardo",      domNoite: "Raul",         folga: "Marcus Túlio" },
  { sabDia: "Marcus Túlio", sabNoite: "Carlos",       domDia: "Emanoel",      domNoite: "Ricardo",      folga: "Raul" },
  { sabDia: "Raul",         sabNoite: "Marcus Túlio", domDia: "Carlos",       domNoite: "Emanoel",      folga: "Ricardo" },
  { sabDia: "Ricardo",      sabNoite: "Raul",         domDia: "Marcus Túlio", domNoite: "Carlos",       folga: "Emanoel" },
  { sabDia: "Emanoel",      sabNoite: "Ricardo",      domDia: "Raul",         domNoite: "Marcus Túlio", folga: "Carlos" },
];

// Rotação de FDS NOVA — escada de 6 semanas com as 6 pessoas (4 trabalham + 2 folgam).
// A tabela inteira é GERADA a partir desta ordem de rodízio: cada pessoa avança uma
// estação por semana. Estações (em ordem): Sáb Dia, Sáb Noite, Dom Dia, Dom Noite,
// Folga, Folga. Vale para os fins de semana a partir de WEEKEND_CHANGE.
export const WEEKEND_ROSTER = ["Carlos", "Marcus Túlio", "Raul", "Ricardo", "Emanoel", "Alice"];
// Sábado da Semana 1 da escada nova (18/07/2026). Fins de semana >= esta data usam a
// escada nova; anteriores mantêm WEEKEND_CYCLE. ⚠ Mover isto recalcula a escala.
export const WEEKEND_CHANGE = new Date(2026, 6, 18);

// The Saturday corresponding to Week 1 of the 5-week weekend rotation.
// Changing ANCHOR shifts the entire schedule history — requires full rotation recalibration.
export const ANCHOR      = new Date(2026, 5, 13);
// Window generated by buildSchedule(). To extend the schedule, update RANGE_END only.
export const RANGE_START = new Date(2026, 5, 8);
export const RANGE_END   = new Date(2027, 5, 30);

// ─── LABELS ──────────────────────────────────────────────────────────────────

export const DOW         = ["Domingo","Segunda","Terça","Quarta","Quinta","Sexta","Sábado"];
export const DOW_SHORT   = ["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"];
export const MONTHS      = ["Janeiro","Fevereiro","Março","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"];
export const MONTHS_SHORT = ["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"];

// ─── HELPERS ─────────────────────────────────────────────────────────────────

export const MS_DAY  = 86400000;
export const dayKey  = (d) => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
export const sameDay = (a, b) => a.getFullYear()===b.getFullYear() && a.getMonth()===b.getMonth() && a.getDate()===b.getDate();
export const fmtDS   = (str) => str ? `${str.slice(8)}/${str.slice(5,7)}` : "";

export function durationHours(inicio, fim) {
  if (!inicio || !fim) return 0;
  const [hi, mi] = inicio.split(":").map(Number);
  const [hf, mf] = fim.split(":").map(Number);
  let start = hi * 60 + mi;
  let end   = hf * 60 + mf;
  if (end <= start) end += 24 * 60; // shift crosses midnight (e.g. 23:00–04:00)
  return (end - start) / 60;
}

// Soma as horas de uma lista de lançamentos MESCLANDO intervalos que se sobrepõem
// (união), em vez de somar cada um isolado — evita contar tempo em dobro quando o
// usuário registra duas atividades no mesmo período. Trata turnos que cruzam a
// meia-noite (fim <= início) e não funde lançamentos de dias diferentes.
// Só deve ser usado por tipo (HE com HE, Comp com Comp): tipos diferentes têm
// remuneração distinta e não devem se cancelar.
export function mergedHours(entries) {
  const dayIdx = (d) => {
    const [y, m, dd] = String(d).split("-").map(Number);
    return Date.UTC(y, m - 1, dd) / MS_DAY;
  };
  const intervals = entries
    .map(e => {
      const [hi, mi] = String(e.inicio || "").split(":").map(Number);
      const [hf, mf] = String(e.fim    || "").split(":").map(Number);
      if ([hi, mi, hf, mf].some(Number.isNaN)) return null;
      const base = dayIdx(e.data) * 1440;
      const s = base + hi * 60 + mi;
      let en  = base + hf * 60 + mf;
      if (en <= s) en += 1440; // cruza meia-noite
      return [s, en];
    })
    .filter(Boolean)
    .sort((a, b) => a[0] - b[0]);

  let total = 0, curS = null, curE = null;
  for (const [s, e] of intervals) {
    if (curS === null)      { curS = s; curE = e; }
    else if (s < curE)      { if (e > curE) curE = e; } // colide → estende a união
    else                    { total += curE - curS; curS = s; curE = e; } // gap → fecha bloco
  }
  if (curS !== null) total += curE - curS;
  return total / 60;
}

export function fmtHM(hoursDecimal) {
  const totalMin = Math.round(hoursDecimal * 60);
  const h = Math.floor(totalMin / 60);
  const m = totalMin % 60;
  return `${h}:${String(m).padStart(2, "0")}`;
}

export const brl = (v) => v.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });

// ─── LÓGICA DE ESCALA ────────────────────────────────────────────────────────

// Returns 0–4 index into WEEKEND_CYCLE for the given Saturday.
// The "+5 before %5" keeps the result positive for dates before ANCHOR.
export function cycleIndex(saturday) {
  const diff = Math.round((saturday.getTime() - ANCHOR.getTime()) / (7 * MS_DAY));
  return ((diff % 5) + 5) % 5;
}

// Atribuição de FDS para um dado sábado. Escolhe a rotação pela data:
//   • sábado < WEEKEND_CHANGE → ciclo antigo (5 semanas, 1 folga) — preserva histórico.
//   • sábado >= WEEKEND_CHANGE → escada nova (6 semanas), GERADA do WEEKEND_ROSTER:
//     estação s na semana w = roster[(s - w) mod N]; cada pessoa avança 1 estação/semana.
// Retorna sempre { cycleWeek, sabDia, sabNoite, domDia, domNoite, folga: string[] }.
export function weekendAssignment(saturday) {
  if (saturday.getTime() >= WEEKEND_CHANGE.getTime()) {
    const N = WEEKEND_ROSTER.length; // 6
    const diff = Math.round((saturday.getTime() - WEEKEND_CHANGE.getTime()) / (7 * MS_DAY));
    const w = ((diff % N) + N) % N;
    const cell = (s) => WEEKEND_ROSTER[(((s - w) % N) + N) % N];
    return {
      cycleWeek: w + 1,
      sabDia: cell(0), sabNoite: cell(1), domDia: cell(2), domNoite: cell(3),
      folga: [cell(4), cell(5)],
    };
  }
  const idx = cycleIndex(saturday);
  const rot = WEEKEND_CYCLE[idx];
  return {
    cycleWeek: idx + 1,
    sabDia: rot.sabDia, sabNoite: rot.sabNoite, domDia: rot.domDia, domNoite: rot.domNoite,
    folga: [rot.folga],
  };
}

// Pessoas de um turno — normaliza `person` (string legada) e `persons[]` (multi).
// Todo leitor da escala deve usar isto em vez de acessar shift.person direto.
export function shiftPeople(shift) {
  if (shift?.persons?.length) return shift.persons;
  if (shift?.person) return [shift.person];
  return [];
}

// Parseia "HH:MM – HH:MM" (aceita –, — ou -) → { sh, sm, eh, em } ou null.
export function parseTimeRange(timeStr) {
  const parts = String(timeStr).split(/[–—-]/).map(s => s.trim());
  if (parts.length < 2) return null;
  const [sh, sm] = (parts[0] || "").split(":").map(Number);
  const [eh, em] = (parts[1] || "").split(":").map(Number);
  if ([sh, sm, eh, em].some(Number.isNaN)) return null;
  return { sh, sm, eh, em };
}

// overrides: { [dayKey]: { [idx]: { person?|persons?, period, time, dur, editedAt } | null } }
//   - idx além dos turnos base vira um turno NOVO (feriados/dias custom).
//   - null reverte o slot base ao padrão (e remove um turno extra).
// labels: { [dayKey]: string } — rótulo opcional do dia (ex.: "Feriado").
// Cada turno retornado carrega um `idx` estável (a chave do override), usado pela UI
// para seleção/edição/remoção — não confie na posição no array.
export function buildSchedule(overrides = {}, labels = {}) {
  const days = [];
  for (let t = RANGE_START.getTime(); t <= RANGE_END.getTime(); t += MS_DAY) {
    const d = new Date(t);
    d.setHours(12, 0, 0, 0);
    const dow = d.getDay();
    let base = [], folga = [], cycleWeek = null; // folga sempre array (vazio em dia útil)
    if (dow >= 1 && dow <= 5) {
      base = WEEKDAY_SHIFTS[dow].map(s => ({ ...s }));
    } else {
      const sat = dow === 6 ? d : new Date(d.getTime() - MS_DAY);
      const rot = weekendAssignment(sat);
      cycleWeek = rot.cycleWeek;
      folga = rot.folga; // array (1 pessoa no ciclo antigo, 2 na escada nova)
      base = dow === 6
        ? [{ period:"Dia",  time:"00:00 – 12:00", dur:"12h", person: rot.sabDia   },
           { period:"Noite",time:"12:00 – 00:00", dur:"12h", person: rot.sabNoite }]
        : [{ period:"Dia",  time:"00:00 – 12:00", dur:"12h", person: rot.domDia   },
           { period:"Noite",time:"12:00 – 00:00", dur:"12h", person: rot.domNoite }];
    }
    const dk = dayKey(d);
    const ovDay = overrides[dk] || {};
    const ovIdxs = Object.keys(ovDay).map(Number).filter(Number.isInteger);
    const maxIdx = Math.max(base.length - 1, ...ovIdxs, -1);
    const shifts = [];
    for (let i = 0; i <= maxIdx; i++) {
      const b = base[i];
      const ov = ovDay[String(i)];
      if (ov === null) { if (b) shifts.push({ ...b, idx: i }); continue; } // reverte base; extra some
      if (ov)          { shifts.push({ ...(b || {}), ...ov, idx: i }); continue; }
      if (b)           { shifts.push({ ...b, idx: i }); }
    }
    days.push({ date: new Date(d), dow, shifts, folga, cycleWeek, label: labels[dk] || null });
  }
  return days;
}

// Sequência ordenada de blocos de plantão com início/fim absolutos (ms), derivada
// do shift.time REAL (não de janelas fixas) — então edições de horário e turnos
// custom de feriado são refletidos. Convenção de atribuição de dia preservada:
//   • Dias úteis, idx 0 ("Madrugada"): pernoite que termina em D → começa 23:00 da
//     véspera; exceto segunda, que começa 00:00 (domingo à noite cobre até 00:00).
//   • Demais turnos: começam em D no horário parseado; terminam em D (ou D+1 se cruzam
//     a meia-noite). Turnos extras (idx ≥ base) seguem a mesma regra.
// Cada segmento carrega `people` (array) — turno multi-pessoa é um único bloco.
export function buildOnCallSegments(schedule) {
  const dayMs = (D, off, h, m) => {
    const d = new Date(D); d.setHours(0, 0, 0, 0);
    return d.getTime() + off * MS_DAY + (h * 60 + m) * 60000;
  };
  const segs = [];
  for (const day of schedule) {
    const D = day.date, dow = day.dow, ds = dayKey(D);
    const weekday = dow >= 1 && dow <= 5;
    for (const shift of day.shifts) {
      const tr = parseTimeRange(shift.time);
      if (!tr) continue;
      const startMin = tr.sh * 60 + tr.sm, endMin = tr.eh * 60 + tr.em;
      let start, end;
      if (weekday && shift.idx === 0) {
        start = dow === 1 ? dayMs(D, 0, 0, 0) : dayMs(D, -1, tr.sh, tr.sm); // segunda começa 00:00
        end   = dayMs(D, 0, tr.eh, tr.em);
      } else {
        start = dayMs(D, 0, tr.sh, tr.sm);
        end   = dayMs(D, endMin <= startMin ? 1 : 0, tr.eh, tr.em);        // cruza meia-noite
      }
      segs.push({ start, end, people: shiftPeople(shift), period: shift.period, time: shift.time, dateStr: ds, dow });
    }
  }
  return segs.sort((a, b) => a.start - b.start);
}

// schedule: array de buildSchedule(overrides, labels). `subs` aplica substituições.
// Retorna quem está de plantão AGORA (pode ser mais de uma pessoa em feriado/turno
// multi-pessoa) ou null no vão sem plantão. `people` = [{ person, coveringFor }].
export function currentOnCall(now, schedule, subs = []) {
  const segs = buildOnCallSegments(schedule);
  const t = now.getTime();
  const hits = segs.filter(s => t >= s.start && t < s.end);
  if (!hits.length) return null;
  const people = [];
  for (const s of hits) for (const titular of s.people) {
    const sub = getActiveSub(titular, s.dateStr, subs);
    people.push({ person: sub ? sub.substituto : titular, coveringFor: sub ? titular : null });
  }
  const primary = hits[0];
  return { people, label: `${DOW[primary.dow]} · ${primary.period}`, time: primary.time };
}

// Plantonista anterior e próximo em relação a `now`, com substituições aplicadas.
// Cada lado vem como { people: [nomes], hora }. `hora` formatada (HH:MM, com dia curto
// se for outro dia). Retorna null quando não há vizinho (bordas da escala).
export function adjacentOnCall(now, schedule, subs = []) {
  const segs = buildOnCallSegments(schedule);
  const t = now.getTime();
  const nowDay = dayKey(now);

  const fmtHora = (ms) => {
    const d = new Date(ms);
    const hm = `${String(d.getHours()).padStart(2, '0')}:${String(d.getMinutes()).padStart(2, '0')}`;
    return dayKey(d) === nowDay ? hm : `${DOW_SHORT[d.getDay()]} ${hm}`;
  };
  const shape = (s, ms) => {
    if (!s) return null;
    const people = s.people.map(titular => {
      const sub = getActiveSub(titular, s.dateStr, subs);
      return sub ? sub.substituto : titular;
    });
    return { people, hora: fmtHora(ms) };
  };

  const cur = segs.findIndex(s => t >= s.start && t < s.end);
  let prevSeg = null, nextSeg = null;
  if (cur !== -1) {
    prevSeg = segs[cur - 1] || null;
    nextSeg = segs[cur + 1] || null;
  } else {
    nextSeg = segs.find(s => s.start > t) || null;
    for (let i = segs.length - 1; i >= 0; i--) { if (segs[i].end <= t) { prevSeg = segs[i]; break; } }
  }
  return {
    anterior: shape(prevSeg, prevSeg?.end),   // quando terminou
    proximo:  shape(nextSeg, nextSeg?.start), // quando começa
  };
}

export function getActiveSub(person, dateStr, subs) {
  return subs.find(s => s.titular === person && dateStr >= s.from && dateStr <= s.until) || null;
}

export function getCoverSuggestions(titular, fromStr, untilStr, schedule) {
  return schedule
    .filter(d => {
      const k = dayKey(d.date);
      return k >= fromStr && k <= untilStr && d.shifts.some(s => shiftPeople(s).includes(titular));
    })
    .map(d => {
      const busy = new Set(d.shifts.flatMap(s => shiftPeople(s)));
      const available = Object.keys(PEOPLE).filter(p => p !== titular && !busy.has(p));
      return { date: d.date, dow: d.dow, shifts: d.shifts.filter(s => shiftPeople(s).includes(titular)), available };
    });
}
